config/routes.rb
Rails.application.routes.draw do
  resources :years
  resources :notifications
  resources :settings
  resources :prices
  resources :profiles
  resources :months
  mount RailsAdmin::Engine => '/console', as: 'rails_admin'
  resources :schedulers
  devise_for :users
  resources :rooms
  root 'schedulers#index'
  get "/pages/:page" => "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:minimum_of_day)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :minimum_of_day %>
    <%= form.number_field :minimum_of_day, id: :setting_minimum_of_day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Minimum of day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.minimum_of_day %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Minimum of day:</strong>
  <%= @setting.minimum_of_day %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>