config/routes.rb
Rails.application.routes.draw do
  resources :years
  resources :notifications
  resources :settings
  resources :prices
  resources :profiles
  resources :months
  mount RailsAdmin::Engine => '/console', as: 'rails_admin'
  resources :schedulers
  devise_for :users
  resources :rooms
  root 'schedulers#index'
  get "/pages/:page" => "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :profile
  def price_pretty
    helper.number_to_currency(value, :unit => "R$ ", separator: ",", delimiter: ".",:precision => 2)
  end
  private

  def helper
    @helper ||= Class.new do
      include ActionView::Helpers::NumberHelper
    end.new
  end

end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:name, :value, :start, :end, :profile_id)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: price, local: true) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :price_name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :price_value %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.number_field :start, id: :price_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.number_field :end, id: :price_end %>
  </div>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.text_field :profile_id, id: :price_profile_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Start</th>
      <th>End</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.name %></td>
        <td><%= price.value %></td>
        <td><%= price.start %></td>
        <td><%= price.end %></td>
        <td><%= price.profile %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @price.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @price.value %>
</p>

<p>
  <strong>Start:</strong>
  <%= @price.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @price.end %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @price.profile %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>