config/routes.rb
Rails.application.routes.draw do
  resources :years
  resources :notifications
  resources :settings
  resources :prices
  resources :profiles
  resources :months
  mount RailsAdmin::Engine => '/console', as: 'rails_admin'
  resources :schedulers
  devise_for :users
  resources :rooms
  root 'schedulers#index'
  get "/pages/:page" => "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
	has_one :scheduler
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Sala criada com sucesso.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Sala atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Sala apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :color, :status)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-room">
<div class="col-md-12">
  <div class="form-group">
    <%= form.label :name, "Nome da sala" %>
    <%= form.text_field :name, id: :room_name, :class => "form-control" %>
  </div>
</div>
<div class="col-md-12">
  <div class="form-group">
    <%= form.label :description, "Descrição" %>
    <%= form.text_area :description, id: :room_description , :class => "form-control" %>
  </div>
</div>
<div class="col-md-12">

  <div class="form-group">
    <%= form.label :color, "Cor (hexadecimal, ex: #286AF7)" %>
    <%= form.text_field :color, id: :room_color , :class => "form-control" %>
  </div>
</div>
<div class="col-md-12">

  <div class="form-group">
    <%= form.label :status, "Status" %>
    <%= form.select(:room_status, options_for_select([['Ativada', true], ['Desativada', false]]),  {:prompt => "Selecione"}, {:class => 'form-control'} )%>
  </div>
</div>
<div class="col-md-12">

  <div class="actions">
    <button class="btn btn-primary btn-lg" type="submit">Salvar</button>
  </div>
</div>
</div>
<% end %>

app/views/rooms/edit.html.erb
<div class="col-md-12 pull-left">
    <h3 class="mb20 mt20">Editando sala</h3>
</div>
<div class="col-md-12 pull-left">
    <%= link_to 'Voltar', rooms_path %>
</div>
<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <p id="notice">
  <%= notice %>
  </p>
</div>
<% end %>
<div class="col-md-12 pull-left">
    <h3 class="mb20 mt20">Salas</h3>
</div>
<div class="col-md-12 pull-left">
    <%= link_to 'Nova sala', new_room_path, :class =>  "btn btn-secondary buttons-copy buttons-html5"  %>
</div>
<table class="dataTable no-footer" id="dataTable-firstdesc" role="grid" aria-describedby="dataTable-firstdesc_info" style="width: 1320px;">
    <thead>
        <tr class="bg-primary" role="row">
            <th>ID</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Cor</th>
            <th>Status</th>
            <th colspan="2">Ações</th>
        </tr>
    </thead>
    <tbody>
        <% @rooms.each do |room| %>
        <tr role="row" class="odd">
            <td>
                <%= room.id %>
            </td>
            <td>
                <%= room.name %>
            </td>
            <td>
                <%= room.description %>
            </td>
            <td style="background: <%= room.color %>">
                
            </td>
            <td>
                <% if room.status == true %>
                Ativada
                <% else %>
                Desativada
                
                <% end %>
            </td>
            <td>
                <%= link_to 'Editar', edit_room_path(room) %>
            </td>
            <td>
                <%= link_to 'Apagar', room, method: :delete, data: { confirm: 'Tem certeza?' } %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/rooms/new.html.erb
<div class="col-md-12 pull-left">
    <h3 class="mb20 mt20">Nova sala</h3>
</div>
<div class="col-md-12 pull-left">
    <%= link_to 'Voltar', rooms_path %>
</div>
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @room.color %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>